const fs = require('fs')
const targetFolder = './projects/storefrontstyles/';
const createFileAndFolder = (expectedItem, isFolder, content) => {
  if (!fs.existsSync(expectedItem)) {
    if (isFolder) fs.mkdirSync(expectedItem)
      else fs.writeFileSync(expectedItem, content, 'utf8')
  } else {
  }
};

exports.initProject = () => {
  createFileAndFolder(targetFolder + 'cuong-sass', true)
  createFileAndFolder(targetFolder + 'cuong-sass/base', true)
  createFileAndFolder(targetFolder + 'cuong-sass/libs', true)
  createFileAndFolder(targetFolder + 'cuong-sass/vendors', true)
  createFileAndFolder(targetFolder + 'cuong-sass/responsive', true)

  createFileAndFolder(targetFolder + 'cuong-sass/base/reset.scss', false, fs.readFileSync('./gulp-helpers/init-data/reset.txt'))
  createFileAndFolder(targetFolder + 'cuong-sass/base/colors.scss', false, fs.readFileSync('./gulp-helpers/init-data/color.txt'))
  createFileAndFolder(targetFolder + 'cuong-sass/base/fonts.scss', false, fs.readFileSync('./gulp-helpers/init-data/fonts.txt'))
  createFileAndFolder(targetFolder + 'cuong-sass/base/typos.scss', false, fs.readFileSync('./gulp-helpers/init-data/typo.txt'))
  createFileAndFolder(targetFolder + 'cuong-sass/base/icons.scss', false, fs.readFileSync('./gulp-helpers/init-data/icons.txt'))
  createFileAndFolder(targetFolder + 'cuong-sass/libs/width.scss', false, '/* All dimension css properties here */')
  createFileAndFolder(targetFolder + 'cuong-sass/libs/height.scss', false, '/* All dimension css properties here */')
  createFileAndFolder(targetFolder + 'cuong-sass/libs/padding.scss', false, '/* All padding css properties here */')
  createFileAndFolder(targetFolder + 'cuong-sass/libs/margin.scss', false, '/* All margin css properties here */')
  createFileAndFolder(targetFolder + 'cuong-sass/libs/flex.scss', false, '/* All flex css properties here */')
  createFileAndFolder(targetFolder + 'cuong-sass/libs/border.scss', false, '/* All border css properties here */')
  createFileAndFolder(targetFolder + 'cuong-sass/libs/background.scss', false, '/* All background css properties here */')
  createFileAndFolder(targetFolder + 'cuong-sass/libs/overflow.scss', false, '/* All overflow css properties here */')
  createFileAndFolder(targetFolder + 'cuong-sass/libs/position.scss', false, '/* All position css properties here */')
  createFileAndFolder(targetFolder + 'cuong-sass/libs/zindex.scss', false, '/* All zindex css properties here */')
  createFileAndFolder(targetFolder + 'cuong-sass/libs/line-number.scss', false, '/* All zindex css properties here */')
  createFileAndFolder(targetFolder + 'cuong-sass/libs/text-align.scss', false, '/* All text align css properties here */')
  createFileAndFolder(targetFolder + 'cuong-sass/libs/box-size.scss', false, '/* All box sizing css properties here */')
  createFileAndFolder(targetFolder + 'cuong-sass/libs/hover.scss',false, fs.readFileSync('./gulp-helpers/init-data/hover.txt'))
  createFileAndFolder(targetFolder + 'cuong-sass/libs/top.scss', false, '/* All hover effect css properties here */')
  createFileAndFolder(targetFolder + 'cuong-sass/libs/left.scss', false, '/* All hover effect css properties here */')
  createFileAndFolder(targetFolder + 'cuong-sass/libs/right.scss', false, '/* All hover effect css properties here */')
  createFileAndFolder(targetFolder + 'cuong-sass/libs/bottom.scss', false, '/* All hover effect css properties here */')
  createFileAndFolder(targetFolder + 'cuong-sass/libs/support-style.scss', false, '/* All support-style effect css properties here */')
  createFileAndFolder(targetFolder + 'cuong-sass/libs/cursor.scss', false, '/* All cursor css properties here */')
  createFileAndFolder(targetFolder + 'cuong-sass/libs/display.scss', false, '/* All display css properties here */')
  createFileAndFolder(targetFolder + 'cuong-sass/libs/font-size.scss', false, '/* All font weight css properties here */')
  createFileAndFolder(targetFolder + 'cuong-sass/libs/line-height.scss', false, '/* All font weight css properties here */')
  createFileAndFolder(targetFolder + 'cuong-sass/libs/weight.scss', false, '/* All font weight css properties here */')
  createFileAndFolder(targetFolder + 'cuong-sass/libs/font-style.scss', false, '/* All font style css properties here */')
  createFileAndFolder(targetFolder + 'cuong-sass/libs/nth-child.scss', false, '/* All nth-child css properties here */')
  createFileAndFolder(targetFolder + 'cuong-sass/libs/opacity.scss', false, '/* All opacity css properties here */')
  createFileAndFolder(targetFolder + 'cuong-sass/libs/radius.scss', false, '/* All radius css properties here */')
  createFileAndFolder(targetFolder + 'cuong-sass/libs/before.scss', false, fs.readFileSync('./gulp-helpers/init-data/before.txt'))
  createFileAndFolder(targetFolder + 'cuong-sass/libs/after.scss', false, fs.readFileSync('./gulp-helpers/init-data/after.txt'))
  createFileAndFolder(targetFolder + 'cuong-sass/libs/shadow.scss', false, '/* All shadow css properties here */')
  createFileAndFolder(targetFolder + 'cuong-sass/libs/transform.scss', false, '/* All shadow css properties here */')
  createFileAndFolder(targetFolder + 'cuong-sass/libs/max-height.scss', false, fs.readFileSync('./gulp-helpers/init-data/max-height.txt'))
  createFileAndFolder(targetFolder + 'cuong-sass/libs/word-wrap.scss', false, '/* All radius css properties here */')
  createFileAndFolder(targetFolder + 'cuong-sass/libs/word-break.scss', false, '/* All radius css properties here */')
  createFileAndFolder(targetFolder + 'cuong-sass/libs/transition.scss', false, '/* All shadow css properties here */')
  createFileAndFolder(targetFolder + 'cuong-sass/libs/spirit.scss', false, '/* All spirit css properties here */')
  createFileAndFolder(targetFolder + 'cuong-sass/libs/text-color.scss', false, '/* All text-color css properties here */')
  createFileAndFolder(targetFolder + 'cuong-sass/libs/txt-deco.scss', false, fs.readFileSync('./gulp-helpers/init-data/txt-deco.txt'))
  createFileAndFolder(targetFolder + 'cuong-sass/libs/user-select.scss', false, '/* All user-select css properties here */')
  createFileAndFolder(targetFolder + 'cuong-sass/libs/effect.scss', false, fs.readFileSync('./gulp-helpers/init-data/effect.txt'))
  createFileAndFolder(targetFolder + 'cuong-sass/responsive/index.scss', false, '/* Node-1 responisve */')
  createFileAndFolder(targetFolder + 'cuong-sass/vendors/owl-carousel.scss', false, fs.readFileSync('./gulp-helpers/init-data/owl-carousel.txt'))
  createFileAndFolder(targetFolder + 'cuong-sass/main.scss', false, fs.readFileSync('./gulp-helpers/init-data/main-sass.txt'))
}
